### ISSUE TITLE
Flathub release?

### ISSUE THREAD

**Issue by Atkoset** [kutzlect/io.github.thaunknown.miru#1]
I know that it is still pretty early to ask but will there be a Flathub release? I think it would be helpful for reaching more people and would also streamline updates more for when using the 'flatpak update' command, also awesome work so far keep it up. 
:)

**Comment by nlxdodge** [comment]
I have a Steam Deck so it would be nice to have it on Flathub. Or maybe another repository so people can use it as well?
What do you think?

**Comment by alsoGAMER** [comment]
I could do it, @kutzlect any comment?

**Comment by ecficies** [comment]
Alright, I made the [submission](https://github.com/flathub/flathub/pull/4139). @alsoGAMER, I requested you as a collaborator too.

**Comment by alsoGAMER** [comment]
Thanks @kutzlectz, just saw that, tho i think that we should explain how some non standard permissions are used. eg: discord one

**Comment by ecficies** [comment]
We'll see. However, it's used in other manifests as well (without :ro).

**Comment by alsoGAMER** [comment]
Seems like it wasn't needed

**Comment by ecficies** [comment]
Okay, it's [available](https://flathub.org/apps/io.github.thaunknown.miru). Closing.
