### ISSUE TITLE
`LaunchProcess: failed to execvp: xdg-settings`

### ISSUE THREAD

**Issue by alsoGAMER** [kutzlect/io.github.thaunknown.miru#3]
Searching for this specific error online yields a ton of applications having the same issue, i've opened an issue upstream ~~https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1583~~ https://github.com/flatpak/flatpak-xdg-utils/issues/64

**Comment by TingPing** [comment]
This application should simply not call `xdg-settings` inside of flatpak. It cannot change handlers.

**Comment by TingPing** [comment]
At a glance it isn't in Miru's code. It is probably in one of the libraries it uses.

**Comment by alsoGAMER** [comment]
@TingPing Miru uses that executable to configure the handling of the miru: protocol, used for externally loading media into the app - for example miru://w2g/ID is used for joining a groupwatch session

**Comment by TingPing** [comment]
In general this is totally unnecessary. When a mimetype handler is installed and nothing else is registered for that mimetype it becomes the default handler. As I suspect no other `miru://` handler exists it is already always the default.

**Comment by alsoGAMER** [comment]
I see, thank you!

**Comment by TingPing** [comment]
For completeness you can verify this with:

`gio mime x-scheme-handler/miru`

**Comment by alsoGAMER** [comment]
>gio mime x-scheme-handler/miru

This is indeed working, not the other one you sent tho.
