### ISSUE TITLE
[Feature Request]: Wayland Support.

### ISSUE THREAD

**Issue by Aninti** [kutzlect/io.github.thaunknown.miru#5]
### Preflight checklist

- [x] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.

- [x] I have searched the [features list](https://github.com/ThaUnknown/miru#features) for this feature, and I couldn't find it.

- [x] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### Problem Description
Hello, I would like to see Wayland support to improve the experience of using Miru on the SteamDeck. Since SteamOS uses gamescope, a custom Wayland compositor to render out the display. Because of the default being set to X11 whenever you try to drag the window around or scroll down normally to browse. it just feels laggy under Wayland since it is emulating X11 in software mode. Since many Linux distro's are shipping Wayland out of the box now days which are the following but not limited to:

1. SteamOS
2. Ubuntu (since version  21.04)
3. Debian Stable
4. (Not a Linux distro) KDE desktop
5. (Not a Linux distro) Gnome desktop

### Proposed Solution

Enable the flag in electron to increase compatibility amongst Linux users and to auto detect whether the user display session is Wayland or X11 by enabling:

"#ozone-platform-hint=auto" in Chrome/Electron flags

### Final comment

I really appreciate your work on Flatpak version of Miru and getting it to work on the SteamDeck. 
Keep up the good work!

**Comment by ecficies** [comment]
Yeah, well I didn't add it because it was a bit buggy in my experience. However, if you want to use this flag you're free to do so by using PinApp, for example (Flatseal might have an option to change launch options as well, not sure).
You basically just have to add `--ozone-platform-hint=auto` at the end of launch options in this case.
